FROM jodogne/orthanc:0.8.6

MAINTAINER Sebastien Jodogne <s.jodogne@gmail.com>
LABEL Description="Environment to run the integration tests of Orthanc" Vendor="Sebastien Jodogne, University Hospital of Liege"

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install dcmtk python-imaging python-httplib2 python-numpy dicom3tools && rm -rf /var/lib/apt/lists/*

# This binary was generated by running Linux Standard Base on
# "OrthancFramework/Resources/DcmtkTools" in the Orthanc source
# distribution, as DCMTK 3.6.0 does not contain "getscu"
# https://hg.orthanc-server.com/orthanc/file/default/OrthancFramework/Resources/DcmtkTools
RUN wget http://orthanc.osimis.io/ThirdPartyDownloads/linux-standard-base/getscu-3.6.5 -O /usr/bin/getscu
RUN chmod +x /usr/bin/getscu

ENTRYPOINT /bin/bash
